# 告诉系统查用户信息时去哪里找
# files = 先查本地 /etc/passwd
# ldap  = 再查 LDAP 服务器
# 有了这两行，容器里执行 id alice 或 getent passwd alice 就能查到 LDAP 里的用户
passwd:   files ldap
group:    files ldap
shadow:   files ldap
hosts:    files dns
