[global]
    workgroup = WORKGROUP
    security = user
    passdb backend = ldapsam:ldap://openldap:389
    ldap admin dn = cn=admin,dc=nas,dc=local
    ldap suffix = dc=nas,dc=local
    ldap user suffix = ou=users
    ldap ssl = no
    ldap passwd sync = no

[data]
    path = /data
    browseable = yes
    read only = no
    create mask = 0660
    directory mask = 0770
